name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  test: 
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Run tests
        run: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}; cargo test
    
  build:
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Run build
        run: cargo build
        
